from __future__ import annotations


PHENOMENOLOGICAL_DOMAINS: dict[str, dict[str, object]] = {
    "mystical_experience": {
        "label_fr": "experience mystique",
        "definition": "Unite, sacralite, noese, ineffabilite, transcendance du temps/espace ou sentiment d'absolu.",
        "patterns": [
            r"\bmystical\b",
            r"\bspiritual\b",
            r"\bsacred\b",
            r"\bholy\b",
            r"\bdivine\b",
            r"\bgod\b",
            r"\bcosmic\b",
            r"\bunity\b",
            r"\bone with\b",
            r"\bconnected to everything\b",
            r"\bineffable\b",
            r"\bnoetic\b",
            r"\bultimate truth\b",
        ],
    },
    "ego_dissolution": {
        "label_fr": "dissolution de l'ego",
        "definition": "Perte ou dissolution des frontieres du soi, de l'identite ou du sentiment d'etre un sujet separe.",
        "patterns": [
            r"\bego death\b",
            r"\bego loss\b",
            r"\bego dissol",
            r"\blost my ego\b",
            r"\bno self\b",
            r"\bself dissol",
            r"\bidentity dissol",
            r"\bi disappeared\b",
            r"\bi ceased to exist\b",
            r"\bmerged with\b",
            r"\bboundaries dissolved\b",
        ],
    },
    "paranoia": {
        "label_fr": "paranoia",
        "definition": "Suspicion, menace sociale, surveillance, persecution, peur des autres ou des autorites.",
        "patterns": [
            r"\bparanoi",
            r"\bthey were watching\b",
            r"\bbeing watched\b",
            r"\bfollowing me\b",
            r"\bout to get me\b",
            r"\bconspiracy\b",
            r"\bpolice\b",
            r"\bcops?\b",
            r"\bfbi\b",
            r"\bcia\b",
            r"\bgovernment\b",
        ],
    },
    "fear_of_death": {
        "label_fr": "angoisse de mort",
        "definition": "Conviction, peur ou anticipation de mourir, incluant peur somatique d'overdose et mort psychique.",
        "patterns": [
            r"\bthought i (was|would be|might be)? ?dying\b",
            r"\bi (was|am|'m) dying\b",
            r"\bgoing to die\b",
            r"\babout to die\b",
            r"\bafraid .* (die|dying|death)\b",
            r"\bscared .* (die|dying|death)\b",
            r"\bfear(ed|ful)? (of )?(death|dying)\b",
            r"\bfelt like i was dead\b",
            r"\bthought i was dead\b",
            r"\bi('?m| am| was) dead\b",
            r"\bthis is it\b",
            r"\bnear[- ]death\b",
            r"\bheart attack\b",
            r"\boverdose\b",
        ],
    },
    "entity_encounter": {
        "label_fr": "rencontre avec des entites",
        "definition": "Rencontre, presence ou communication avec des entites, presences, aliens, esprits, dieux ou voix personnifiees.",
        "patterns": [
            r"\bentity\b",
            r"\bentities\b",
            r"\bbeing(s)?\b",
            r"\bpresence\b",
            r"\bspirit(s)?\b",
            r"\balien(s)?\b",
            r"\bmachine elves\b",
            r"\bdeit(y|ies)\b",
            r"\bgod(s)?\b",
            r"\bdemon(s)?\b",
            r"\bvoices told\b",
            r"\bcommunicat(ed|ing) with\b",
        ],
    },
    "traumatic_reexperiencing": {
        "label_fr": "reviviscence traumatique",
        "definition": "Retour intrusif de souvenirs traumatiques, flashbacks, abus, violence, culpabilite ou honte traumatique.",
        "patterns": [
            r"\btrauma\b",
            r"\btraumatic\b",
            r"\bflashback(s)?\b",
            r"\babuse\b",
            r"\bassault\b",
            r"\bptsd\b",
            r"\bchildhood\b",
            r"\bmemories came back\b",
            r"\brepressed memor",
            r"\breliv(ed|ing)\b",
            r"\bshame\b",
        ],
    },
    "autobiographical_insight": {
        "label_fr": "insight autobiographique",
        "definition": "Compréhension personnelle sur son histoire, ses relations, ses habitudes, ses conflits ou sa trajectoire de vie.",
        "patterns": [
            r"\binsight\b",
            r"\brealized\b",
            r"\bi understood\b",
            r"\bi saw that\b",
            r"\bmy life\b",
            r"\bmy childhood\b",
            r"\bmy family\b",
            r"\bmy relationships?\b",
            r"\bpattern(s)? in my life\b",
            r"\blearned about myself\b",
            r"\btherapy\b",
            r"\bhealing\b",
        ],
    },
    "religious_feeling": {
        "label_fr": "sentiment religieux",
        "definition": "Reference religieuse, priere, peche, salut, revelation, Dieu, enfer, paradis ou jugement moral religieux.",
        "patterns": [
            r"\breligio",
            r"\bgod\b",
            r"\bjesus\b",
            r"\bchrist\b",
            r"\bprayer\b",
            r"\bpray(ed|ing)?\b",
            r"\bheaven\b",
            r"\bhell\b",
            r"\bsin\b",
            r"\bsatan\b",
            r"\bangel(s)?\b",
            r"\bsoul\b",
        ],
    },
    "interoceptive_threat": {
        "label_fr": "menace interoceptive",
        "definition": "Signaux corporels inhabituels interpretes comme dangereux ou non controlables.",
        "patterns": [
            r"\bheart (attack|rate|beating|pounding|racing)\b",
            r"\bpalpitation",
            r"\bchest pain\b",
            r"\bcould(n't| not) breathe\b",
            r"\bbreath(ing)?\b",
            r"\bvomit",
            r"\bnausea",
            r"\bshaking\b",
            r"\btrembl",
            r"\bpoison",
            r"\boverdose",
        ],
    },
    "loss_of_control": {
        "label_fr": "perte de controle",
        "definition": "Incapacite percue a controler le corps, les pensees, les emotions, le comportement ou la situation.",
        "patterns": [
            r"\blost control\b",
            r"\bout of control\b",
            r"\bcould(n't| not) control\b",
            r"\bno control\b",
            r"\bcould(n't| not) stop\b",
            r"\btrapped\b",
            r"\bstuck\b",
            r"\bspiral(ed|ing)? (out|down|into)\b",
            r"\bdownward spiral\b",
            r"\bthought spiral\b",
        ],
    },
    "fear_of_madness": {
        "label_fr": "peur de devenir fou",
        "definition": "Peur de perdre la raison, de rester psychotique, schizophrene ou de ne jamais revenir.",
        "patterns": [
            r"\bgoing crazy\b",
            r"\bwent crazy\b",
            r"\bgo insane\b",
            r"\bwent insane\b",
            r"\blosing my mind\b",
            r"\blost my mind\b",
            r"\bpsychosis\b",
            r"\bpsychotic\b",
            r"\bschizophren",
            r"\bnever be sane\b",
            r"\bnever come back\b",
        ],
    },
    "derealization_depersonalization": {
        "label_fr": "derealisation/depersonnalisation",
        "definition": "Monde ou soi devenu irreel, etranger, artificiel, dissocie ou onirique.",
        "patterns": [
            r"\bunreal\b",
            r"\bderealization\b",
            r"\bdepersonalization\b",
            r"\bnot real\b",
            r"\bdream\b",
            r"\blike a movie\b",
            r"\boutside my body\b",
            r"\bwatching myself\b",
            r"\bdissociat",
        ],
    },
    "time_distortion": {
        "label_fr": "distorsion temporelle",
        "definition": "Temps ralenti, arrete, infini, cyclique ou impossible a evaluer.",
        "patterns": [
            r"\btime stopped\b",
            r"\btime slowed\b",
            r"\btime was\b",
            r"\bforever\b",
            r"\beternity\b",
            r"\binfinite\b",
            r"\bnever end\b",
            r"\bstuck in time\b",
        ],
    },
    "thought_loop": {
        "label_fr": "boucle de pensee",
        "definition": "Repetition intrusive de pensees, scenes, phrases ou raisonnements circulaires.",
        "patterns": [
            r"\bthought loop\b",
            r"\bloops?\b",
            r"\brepeating\b",
            r"\bover and over\b",
            r"\bagain and again\b",
            r"\bcycle\b",
            r"\bspiral(ed|ing)? (out|down|into)\b",
            r"\bdownward spiral\b",
            r"\bthought spiral\b",
            r"\bruminat",
        ],
    },
    "perceptual_overload": {
        "label_fr": "surcharge perceptive",
        "definition": "Intensite sensorielle excessive, hallucinations envahissantes, synesthesie ou perte de stabilite perceptive.",
        "patterns": [
            r"\boverwhelm(ed|ing)?\b",
            r"\btoo intense\b",
            r"\bvisuals\b",
            r"\bhallucination",
            r"\bpatterns\b",
            r"\bgeometric\b",
            r"\bsynesthesia\b",
            r"\bsounds? .* intense\b",
            r"\blights? .* intense\b",
        ],
    },
    "acceptance_surrender": {
        "label_fr": "acceptation/surrender",
        "definition": "Bascule par acceptation, let go, abandon du controle, consentement a traverser l'experience.",
        "patterns": [
            r"\baccept",
            r"\bsurrender",
            r"\blet go\b",
            r"\bletting go\b",
            r"\bgive in\b",
            r"\bgave in\b",
            r"\bstop fighting\b",
            r"\bstopped fighting\b",
            r"\bembrace",
            r"\ballowed it\b",
        ],
    },
    "integration_positive_afterwards": {
        "label_fr": "integration positive apres coup",
        "definition": "Relecture positive, apprentissage, gratitude, prudence, transformation ou potentiel therapeutique apres la crise.",
        "patterns": [
            r"\blearned\b",
            r"\blesson\b",
            r"\bmeaningful\b",
            r"\bpositive\b",
            r"\bgrateful\b",
            r"\bchanged my life\b",
            r"\btherapeutic\b",
            r"\bhealing\b",
            r"\bintegrat",
            r"\brespect for\b",
        ],
    },
    "negative_aftermath": {
        "label_fr": "sequelles negatives",
        "definition": "Anxiete persistante, derealisation durable, traumatisation, regrets ou deterioration apres l'experience.",
        "patterns": [
            r"\btraumatized\b",
            r"\btraumatised\b",
            r"\bptsd\b",
            r"\bflashbacks?\b",
            r"\bpanic attacks?\b",
            r"\banxiety .* weeks?\b",
            r"\bmonths? later\b",
            r"\bnever been the same\b",
            r"\bregret\b",
            r"\bpost trip\b",
        ],
    },
}


PHENOMENOLOGICAL_MODEL_LABELS = list(PHENOMENOLOGICAL_DOMAINS)
